[package]
name = "rust"
version = "0.1.0"
authors = ["Folyd <lyshuhow@gmail.com>"]
edition = "2018"

[[bin]]
name = "crates-index"
path = "src/main.rs"

[dependencies]
serde = "1.0.102"
tokio = "0.2.0-alpha.6"
reqwest = { version="0.10.0-alpha.2" , features=["json"] }
serde_json = "1.0.41"
serde_derive = "1.0.102"
futures = "0.3.1"
minifier = "0.0.33"
