[package]
name = "rust-search-extension"
version = "0.1.0"
authors = ["Folyd <lyshuhow@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.102"
minifier = "0.0.36"
unicode-segmentation = "1.6.0"
futures = "0.3.1"
tokio = { version = "0.2", features = ["macros", "time"] }
reqwest = { version = "0.10", features = ["json"] }
select = "0.4.3"
csv = "1.1.3"
semver = { version = "0.9.0", features = ["ci"] }
tar = "0.4.26"
libflate = "0.1.27"
rayon = "1.3.0"
regex = "1.3.9"
argh = "0.1.4"
anyhow = "1.0.34"
