[package]
name = "rust-search-extension"
version = "0.1.0"
authors = ["Folyd <lyshuhow@gmail.com>"]
edition = "2018"

[features]
crates-index = ["csv","semver","tar","libflate", "rayon"]
books-index = ["futures","tokio","reqwest","select"]
labels-index = ["tokio","reqwest"]
caniuse-index = []
default = ["crates-index"]

[dependencies]
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.102"
minifier = "0.0.36"
unicode-segmentation = "1.6.0"
futures = { version = "0.3.1", optional=true }
tokio = { version="0.2", features=["macros", "time"], optional=true }
reqwest = { version="0.10" , features=["json"], optional=true }
select = { version= "0.4.3", optional=true }
csv = { version = "1.1.3", optional=true }
semver = { version="0.9.0", features=["ci"], optional=true }
tar = { version = "0.4.26", optional=true }
libflate = { version="0.1.27", optional=true }
rayon = { version="1.3.0", optional=true }
