name: Build index
on:
  workflow_dispatch:

jobs:
  build:
    name: Build index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build index"
        run: |
          cd rust
          RUST_BACKTRACE=full cargo run --target-dir /tmp --manifest-path=rust/Cargo.toml books -d /tmp/public/index/books.js
          RUST_BACKTRACE=full cargo run --target-dir /tmp --manifest-path=rust/Cargo.toml lints -d /tmp/public/index/lints.js
          RUST_BACKTRACE=full cargo run --target-dir /tmp --manifest-path=rust/Cargo.toml labels -d /tmp/public/index/labels.js
          git clone https://github.com/jplatte/caniuse.rs.git
          RUST_BACKTRACE=full cargo run --target-dir /tmp --manifest-path=rust/Cargo.toml caniuse -r /tmp/caniuse -d /tmp/public/index/caniuse.js
          zip /tmp/index.zip /tmp/*.js
      - name: "Upload Index Artifact"
        uses: actions/upload-artifact@master
        with:
          name: index.zip
          path: /tmp/index.zip

