name: docs

on: push

jobs:
  build:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deloy docs
      run: ./scripts/deploy-docs.sh
