name: docs

on:
  repository_dispatch:
    types: deploy-docs

jobs:
  build:
    name: Deploy to now branch
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: 'recursive'
    - name: Deloy docs
      run: ./scripts/deploy-docs.sh
