name: docs

on:
  repository_dispatch:
    types: deploy-docs

jobs:
  build:
    name: Deploy to now branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Deloy docs
      run: ./scripts/deploy-docs.sh
