name: "Release the web extension artifacts"
on:
  create:
    tags:
      - v*

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: extension

      - name: "Upload Artifact"
        uses: actions/upload-artifact@master
        with:
          name: target
          path: ${{ steps.web-ext-build.outputs.target }}
